### PR TITLE
include validations in `ActiveModel::Model`

### PR DESCRIPTION
**Pull request by seanpdoyle**
`ActiveRecord::Base` extends `ActiveModel::Model`

Also, added `Gemfile` so that `bundle install` works

FYI: Couldn't get the tests to run locally. `bundle exec rake test` seems to be a no-op with blank output.

### CODE REVIEW

**Comment by seanpdoyle** [comment]
@kritik @martinkivi is this a good idea?

**Comment by kritik** [comment]
are tests run ok?

**Comment by kritik** [comment]
@seanpdoyle if you pass tst, then I'll merge

**Comment by seanpdoyle** [comment]
closing in favor of #30

**Pull request closed without merging**
